# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g gatsby-cli
  displayName: 'install gatsby'

- script: |
    npm install
    npx gatsby build
  displayName: 'gatsby build'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/srv/public'
- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/public'
    azureSubscription: 'Microsoft Partner Network(5530e2ad-9bb4-4e5e-8f77-ea6bc2b71d9d)'
    Destination: 'AzureBlob'
    storage: 'gatsbyblogstoragenekita'
    ContainerName: '$web'