backend:
  name: github
  branch: master
  repo: Arvutiamblik/amblik
media_folder: static/images
public_folder: /images

collections:
  - name: "main_page_et"
    label: "Main page Estonian"
    slug: "main page et"
    create: true
    identifier_field: Identifier_field
    folder: "src/content/pages"
    fields:
      - {
          label: "Identifier_field",
          name: "Identifier_field",
          widget: "string",
        }
      - { label: "Meta Title", name: "metaTitle", widget: "string" }
      - { label: "Meta Description", name: "metaDescription", widget: "string" }
      - { label: "language code", name: "lang", widget: "string"}
      - { label: "Background Image", name: "img", widget: "image"}
      - {
          label: "Top Description",
          name: "TopDescription",
          widget: "object",
          fields:
            [
              { label: "Text", name: "topText", widget: "markdown" },
              { label: "Button", name: "topButton", widget: "string" },
            ],
        }
      - { label: "Heading", name: "heading", widget: "string" }

      - {
          label: "intro",
          name: "intro",
          widget: "object",
          fields:
            [
              {
                label: "Blurbs",
                name: "blurbs",
                widget: "list",
                fields:
                  [
                    {
                      label: "blockHeading",
                      name: "blockHeading",
                      widget: "string",
                    },
                    {
                      label: "description",
                      name: "blockDescription",
                      widget: "markdown",
                    },
                    {
                      label: "button",
                      name: "buttonPlaceholder",
                      widget: "string",
                    },
                  ],
              },
            ],
        }
      - {
          label: "TextCards",
          name: "TextCards",
          widget: "object",
          fields:
            [
              {
                label: "TextCard",
                name: "TextCard",
                widget: "list",
                fields:
                  [
                    { label: "title", name: "title", widget: "string" },
                    {
                      label: "description",
                      name: "description",
                      widget: "markdown",
                    },
                    { label: "button", name: "button", widget: "string" },
                  ],
              },
            ],
        }
      - { label: "Footer", name: "footer", widget: "markdown" }

      collections: "article"
      - name: "main_page_et"
      label: "Main page Estonian"
      slug: "main page et"
      create: true
      identifier_field: Identifier_field
      folder: "src/content/pages"
      fields:
      -  {
          label: "Identifier_field",
          name: "Identifier_field",
          widget: "string",
        }
      - { label: "Meta Title", name: "metaTitle", widget: "string" }
      - { label: "Meta Description", name: "metaDescription", widget: "string" }
      - { label: "language code", name: "lang", widget: "string"}
      - { label: "Text", name: "text", widget: "string"}
